spring.docker.compose.enabled=false
spring.datasource.url=jdbc:mariadb://localhost:3306/db_videogames
spring.datasource.username=usr_lobato
spring.datasource.password=5116
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true